import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/frameone">FrameOne</Link>
        </li>
        <li>
          <Link to="/wireframetwo">WireframeTwo</Link>
        </li>
        <li>
          <Link to="/wireframeone">WireframeOne</Link>
        </li>
        <li>
          <Link to="/chairmansdashboard">Chairmansdashboard</Link>
        </li>
        <li>
          <Link to="/chairmanaccountcreation">Chairmanaccountcreation</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/loginfourteen">LoginFourteen</Link>
        </li>
        <li>
          <Link to="/fa">FA</Link>
        </li>
        <li>
          <Link to="/singlevehiclepolicyrenewal">
            Singlevehiclepolicyrenewal
          </Link>
        </li>
        <li>
          <Link to="/multipolicyrenewal">Multipolicyrenewal</Link>
        </li>
        <li>
          <Link to="/notifications">Notifications</Link>
        </li>
        <li>
          <Link to="/receiptforapaidpolicy">Receiptforapaidpolicy</Link>
        </li>
        <li>
          <Link to="/notificationsone">NotificationsOne</Link>
        </li>
        <li>
          <Link to="/reminderforupcomingpolicyrenewal">
            Reminderforupcomingpolicyrenewal
          </Link>
        </li>
        <li>
          <Link to="/chairman">Chairman</Link>
        </li>
        <li>
          <Link to="/editingpersonaldetails">Editingpersonaldetails</Link>
        </li>
        <li>
          <Link to="/viewingadditionalcardetails">
            Viewingadditionalcardetails
          </Link>
        </li>
        <li>
          <Link to="/cancelpolicy">Cancelpolicy</Link>
        </li>
        <li>
          <Link to="/agentaccountcreation">Agentaccountcreation</Link>
        </li>
        <li>
          <Link to="/logineight">LoginEight</Link>
        </li>
        <li>
          <Link to="/logintwelve">LoginTwelve</Link>
        </li>
        <li>
          <Link to="/faone">FAOne</Link>
        </li>
        <li>
          <Link to="/agentsdashboard">Agentsdashboard</Link>
        </li>
        <li>
          <Link to="/agentprofile">Agentprofile</Link>
        </li>
        <li>
          <Link to="/forgotpasswordresettingpassword">
            ForgotPasswordresettingpassword
          </Link>
        </li>
        <li>
          <Link to="/logintwo">LoginTwo</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/claims">Claims</Link>
        </li>
        <li>
          <Link to="/reportincident">Reportincident</Link>
        </li>
        <li>
          <Link to="/reportingincident">Reportingincident</Link>
        </li>
        <li>
          <Link to="/clickingonanimage">Clickingonanimage</Link>
        </li>
        <li>
          <Link to="/resetpasssword">Resetpasssword</Link>
        </li>
        <li>
          <Link to="/loginthirteen">LoginThirteen</Link>
        </li>
        <li>
          <Link to="/logineleven">LoginEleven</Link>
        </li>
        <li>
          <Link to="/loginfour">LoginFour</Link>
        </li>
        <li>
          <Link to="/drafts">Drafts</Link>
        </li>
        <li>
          <Link to="/loginseven">LoginSeven</Link>
        </li>
        <li>
          <Link to="/loginthree">LoginThree</Link>
        </li>
        <li>
          <Link to="/loginfive">LoginFive</Link>
        </li>
        <li>
          <Link to="/loginsix">LoginSix</Link>
        </li>
        <li>
          <Link to="/loginten">LoginTen</Link>
        </li>
        <li>
          <Link to="/frametwentynine">FrameTwentyNine</Link>
        </li>
        <li>
          <Link to="/loginnine">LoginNine</Link>
        </li>
        <li>
          <Link to="/loginone">LoginOne</Link>
        </li>
        <li>
          <Link to="/reportingincidentone">ReportingincidentOne</Link>
        </li>
        <li>
          <Link to="/dashboardone">DashboardOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
